name = "cybercode230/repay-smart-contract"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'cybercode230/repay-smart-contract'"

[repository]
user = "cybercode230"
project = "repay-smart-contract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[tests]]
name = "repayment.test"
watch = ["validators", "lib", "tests"]

[config]