name = "itsinda/loan_fixed"
version = "0.0.0"
compiler = "v1.1.5"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'itsinda/loan_fixed'"

[repository]
user = "itsinda"
project = "loan_fixed"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.0.0"
source = "github"

[config]
